# Workflow - Foi desabilitado no Painel Actions do Github
name: Test Validation

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Validation on Pull Request (INFRA AWS)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: IaC Test
      env:
        COMMAND_IAC: terraform
      run: |
        cd mod-01/infraestrutura
        $COMMAND_IAC init
        $COMMAND_IAC validate
        $COMMAND_IAC plan
